name: build-slides
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
    marp-build-and-deploy:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Ensure build dir exists
          run: mkdir -p web

        - name: Build html slides
          uses: docker://marpteam/marp-cli:v3.4.0
          with:
            args: --html -o web/slides/ -I slides -c .vscode/settings.json
          env:
            MARP_USER: root:root

        - name: Build pdf slides
          uses: docker://marpteam/marp-cli:v3.4.0
          with:
            args: --pdf --allow-local-files -o web/pdf/ -I slides -c .vscode/settings.json
          env:
            MARP_USER: root:root

        - name: copy static content (images, css, etc)
          run: sudo find slides \( -name "*.png" -or -name "*.svg" -or -name "*.css" -or -name "*.jpg" \) -exec sh -c 'mkdir -p web/"$(dirname "{}")"' \; -exec cp {} web/{} \; -exec cp {} web/{} \;

        - name: copy gpu pdf
          run: sudo cp slides/04-GPU-model/gpu-slides.pdf web/slides/04-GPU-model/gpu-slides.pdf
        - name: override gpu slide pdf
          run: sudo cp slides/04-GPU-model/gpu-slides.pdf web/pdf/04-GPU-model/01-GPU-model.pdf

        - name: Deploy 🚀
          uses: JamesIves/github-pages-deploy-action@v4
          with:
            branch: gh-pages
            folder: web # The folder the action should deploy.


